# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SDpG9GF_KPvLP-eqgYYJfsUlfTXqdd9
"""

from flask import Flask, render_template, request
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import os

app = Flask(__name__)
model = load_model("weather_classifier_vgg16.h5")
class_labels = ['badai', 'cerah', 'hujan', 'mendung']

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        img_file = request.files["image"]
        img_path = os.path.join("static", img_file.filename)
        img_file.save(img_path)

        img = image.load_img(img_path, target_size=(224, 224))
        x = image.img_to_array(img) / 255.0
        x = np.expand_dims(x, axis=0)
        pred = model.predict(x)
        label = class_labels[np.argmax(pred)]

        return render_template("index.html", label=label, img_path=img_path)
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)